spring.application.name=spring-notify-engine
spring.datasource.url=jdbc:postgresql://localhost:5432/notifydb
spring.datasource.username=notify
spring.datasource.password=notify
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8080
server.tomcat.threads.max=1000
notification.max-retry=3
